input:
  - data: item/post/page object with data
  - file: data filename
  - i: the index of current file in the list 
  - len: the lenth of the files list
output:
  - key: |
      the name of the store, for instance html for the html output
      the key also a folder of the ./src/render/{key}/ to process after functions,
      for instance ./src/render/html/styles.js
  - out: the result data
