image: node:21
before_script:
  - npm install
cache:
  paths:
    - web/node_modules/
    - web/nano/
    - web/dist/
    - web/logs/
pages:
  stage: deploy
  script:
    - npm run init
    - npm run dist
  artifacts:
    paths:
      - web/dist
  only:
    - main
  publish: web/dist
