image: node:21
# Functions that should be executed before the build script is run
before_script:
  - npm install
cache:
  paths:
    - web/node_modules/
    - web/nano/
    - web/dist/
    - web/logs/

pages:
  stage: deploy
  script:
    - pwd
    - npm run dist
  artifacts:
    paths:
    - web/dist
  only:
    - main  # Change this to the branch you want to trigger the pipeline
  publish: web/dist
  # rules:
  #   # This ensures that only pushes to the default branch will trigger
  #   # a pages deploy
  #   - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
