types:
  nwSection: /[\d]+(\.{1}[\d]+)*\.{0,1}/
  nwDataUri: /^[a-zA-Z0-9\-_./]+$/
  nwDataUriSection: # {nwDataUri}:{nwSection}
  nwFileUri: /^[a-zA-Z0-9\-_./]+(\.[\w\d]{2,})$/
  nwFileName: /[^\s]{2,}/
  nwClassName: # DOMTokenList
  nwText: /.+/
  nwNano: # nan•web YAML format representing the structure of HTML
  nwFile:
    - object:
      src: nwFileUri
      name: nwFileName # <span class="h1">{name}</span>
      class: nwClassName # li.{class}
      text: nwText # <div class="p-3 py-0"><%= p.text %></div>
      filesClass: nwClassName # ul.files.{filesClass}
      $ref: nwDataUriSection # {nwDataUri}:{nwSection}
      files: nwFiles
    - string: nwFileUri # <a href="{filePrefix}{file}" %>">{file}</a>
  nwFiles: "[nwFile]"
data:
  - requires:
    - $extractDesc: boolean; Extract description from the content if desc is not provided.
    - $extend: nwDataUri; Extends by the data of provided file (uri).
    - $refer: nwDataUri; Extends by the data of provided file (uri) as a different language.
  - optional:
    - $catalog: |
        nwDataUri; Defines the current catalog uri.
                   Use it per file only, when you use for the children, in a way to
                   defined in _.yaml folder options it won't collect the dependecies
                   for rendering of the category/catalog.
    - $theme: string; The theme name to render data.
    - $layout: string; The layout name to render data.
    - $redirect: nwDataUri; Redirects the page to provided uri.
    - category: |
        string; Defines the current data file as a category.
                Does not work with the $extend, $refer.
                When defined in nested posts this page won't be part of any posts.
    - page:
        category: |
          string; Connect the current data file to a category.
    - files: |
        nwFiles; Files attached to the document
  - produces:
    - $uri: nwDataUri; The current data uri, includes language code.
    - $uid: nwDataUid; The current data unique ID, does not include language code. $uri - language code.
    - $alternates: |
        { lang: nwDataUri }; A map of alternated urls.
    - $currentLang: nwDataLang; The current language.
    - lang: string; The current language code.
    - env: |
        { key: value }; A map of allowed ENV variables.
    - version: string; The version number.
    - all: |
        { nwDataUri: { stat, data } }; All loaded files with their data and stat.
    - categories: nwCategoriesDict; dictionary of the categories.
runtime:
    - $rendering: boolean; Option to handle $private, $public nan•data and ?version={runtime['versionSlug']}.
cache:
  - controls:
    - changes of the file
    - changes of the parent files (every directory settings)
    - changes of the $extend file
    - changes of the $refer file